# coding: utf-8

"""
    Reya DEX Trading API v2

    API for Reya Network's decentralized exchange. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorCode(str, Enum):
    """
    Standardized error codes for API responses
    """

    """
    allowed enum values
    """
    SYMBOL_NOT_FOUND = 'SYMBOL_NOT_FOUND'
    NO_ACCOUNTS_FOUND = 'NO_ACCOUNTS_FOUND'
    NO_PRICES_FOUND_FOR_SYMBOL = 'NO_PRICES_FOUND_FOR_SYMBOL'
    CANDLE_DATA_NOT_FOUND = 'CANDLE_DATA_NOT_FOUND'
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorCode from a JSON string"""
        return cls(json.loads(json_str))


