# coding: utf-8

"""
    Reya DEX Trading API v2

    API for Reya Network's decentralized exchange. 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from reya_v2_api.models.execution_type import ExecutionType
from reya_v2_api.models.side import Side
from typing import Optional, Set
from typing_extensions import Self

class SpotExecution(BaseModel):
    """
    SpotExecution
    """ # noqa: E501
    exchange_id: Union[StrictFloat, StrictInt] = Field(description="Exchange identifier", alias="exchangeId")
    symbol: StrictStr = Field(description="Asset pair symbol (e.g., BTCRUSD)")
    account_id: Union[StrictFloat, StrictInt] = Field(description="Account identifier", alias="accountId")
    side: Side
    qty: StrictStr = Field(description="Quantity to liquidator")
    price: Optional[StrictStr] = Field(default=None, description="Execution price")
    fee: StrictStr = Field(description="Fee paid")
    type: ExecutionType
    timestamp: Union[StrictFloat, StrictInt] = Field(description="Execution timestamp (milliseconds)")
    __properties: ClassVar[List[str]] = ["exchangeId", "symbol", "accountId", "side", "qty", "price", "fee", "type", "timestamp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpotExecution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpotExecution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exchangeId": obj.get("exchangeId"),
            "symbol": obj.get("symbol"),
            "accountId": obj.get("accountId"),
            "side": obj.get("side"),
            "qty": obj.get("qty"),
            "price": obj.get("price"),
            "fee": obj.get("fee"),
            "type": obj.get("type"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


