from enum import Enum

class CancelReason(Enum): 
  NO_LIQUIDITY = "NO_LIQUIDITY"
  IOC_REMAINDER = "IOC_REMAINDER"
  SELF_TRADE_PREVENTION = "SELF_TRADE_PREVENTION"
  GTT_EXPIRED = "GTT_EXPIRED"
  USER_CANCEL = "USER_CANCEL"
  MASS_CANCEL = "MASS_CANCEL"
  CANCEL_ALL_AFTER = "CANCEL_ALL_AFTER"
  FEED_RESET = "FEED_RESET"
  RISK_CANCELLED = "RISK_CANCELLED"