from enum import Enum

class CancelReason(Enum): 
  NO_LIQUIDITY = "NO_LIQUIDITY"
  IOC_REMAINDER = "IOC_REMAINDER"
  SELF_TRADE_PREVENTION = "SELF_TRADE_PREVENTION"
  PROTECTIVE_SELF_TRADE_SWEEP = "PROTECTIVE_SELF_TRADE_SWEEP"
  GTT_EXPIRED = "GTT_EXPIRED"
  USER_CANCEL = "USER_CANCEL"
  MASS_CANCEL = "MASS_CANCEL"
  CANCEL_ALL_AFTER = "CANCEL_ALL_AFTER"
  FEED_RESET = "FEED_RESET"
  RISK_CANCELLED = "RISK_CANCELLED"
  RISK_REJECTED = "RISK_REJECTED"
  OCO_SIBLING_FIRED = "OCO_SIBLING_FIRED"
  POSITION_CLOSED = "POSITION_CLOSED"
  BAND_VIOLATION = "BAND_VIOLATION"