from __future__ import annotations
from typing import Any, Dict, Optional
from pydantic import model_serializer, model_validator, BaseModel, Field
from sdk.async_exec_api.order_status import OrderStatus
from sdk.async_exec_api.cancel_reason import CancelReason
class CreateOrderResponse(BaseModel): 
  status: OrderStatus = Field(description='''Order status. An armed but not-yet-fired `STOP_LOSS` / `TAKE_PROFIT` trigger surfaces as `OPEN`, and so does the resting child it fires into; the `triggered` flag on the `Order` schema tells the two apart.''')
  exec_qty: Optional[str] = Field(default=None, alias='''execQty''')
  cum_qty: Optional[str] = Field(default=None, alias='''cumQty''')
  order_id: str = Field(description='''Engine-assigned order ID, generated for all order types including IOC. A no-cross IOC still receives an ID and is returned with status CANCELLED (it never rests).''', alias='''orderId''')
  client_order_id: Optional[str] = Field(description='''Client-provided order ID echoed back from the request, as a decimal string (`uint64`).''', default=None, alias='''clientOrderId''')
  cancel_reason: Optional[CancelReason] = Field(description='''Why an order reached a terminal `CANCELLED` status. `cancelReason` / `cancelReasonMessage` are present if and only if `status` is `CANCELLED`; they are omitted entirely (not `null`, not `""`) otherwise. Matching-engine `UNSPECIFIED` or unknown reasons map to omission. `NO_LIQUIDITY` (IOC executed zero quantity because no fillable liquidity was available at its limit) and `IOC_REMAINDER` (IOC partially filled and the remaining quantity was cancelled because no more executable opposite liquidity was available) are returned on `createOrder` / `modifyOrder` responses; `GTT_EXPIRED`, `USER_CANCEL`, `MASS_CANCEL` and `CANCEL_ALL_AFTER` are delivered on the `walletOrderChanges` stream. `SELF_TRADE_PREVENTION` can appear on `createOrder` / `modifyOrder` responses and on `walletOrderChanges` when a modified resting order crosses as taker. It cancels the aggressor (taker) only; your resting order is left untouched. If an IOC partially fills and its remaining quantity is then cancelled by self-trade prevention, the response keeps the fill quantities and reports `cancelReason: SELF_TRADE_PREVENTION`; `IOC_REMAINDER` is used only when matching stops without a self-cross. `FEED_RESET` is generated by the API layer (not the matching engine): when the market-data feed is reset — e.g. a matching-engine reseed — every resting order is delivered on the `walletOrderChanges` stream as `CANCELLED` with `cancelReason: FEED_RESET`, immediately followed by fresh order events that re-publish your current open orders. It does not mean your orders were cancelled on the exchange; treat it as a signal to discard and rebuild your local order view, reconciling against `GET /v2/wallet/{address}/openOrders` if needed. `RISK_CANCELLED` means one of your resting orders was cancelled by the exchange's pre-trade risk checks at the moment it was about to be matched — typically because your account can no longer support the position that fill would create. Which individual check refused it is NOT published — `cancelReasonMessage` is a fixed explanatory string per `cancelReason`, so do not parse it or branch on it. It is delivered on the `walletOrderChanges` stream only, and never on a `createOrder` / `modifyOrder` response: an order refused by risk checks at admission was never created and comes back as an error response carrying a `RequestErrorCode` instead, so a cancellation always refers to an order that existed and has an `orderId`. If the cancelled order had already partially filled, the cancellation keeps its fill quantities. The incoming order that triggered the match is not itself cancelled and the match cycle is not aborted: it continues against the remaining book, which may leave it filling at worse levels, or not at all. The remaining reasons belong to protective stops and are delivered on the `walletOrderChanges` stream. `OCO_SIBLING_FIRED`: a stop-loss and a take-profit on the same account and market are one-cancels-the-other, so a fire that COMMITS cancels the other leg — including a fire that ends up filling nothing, which still consumes both legs. It is written only where a child order was actually created: a fire refused before that point retires both legs under the reason for the refusal instead (`POSITION_CLOSED` or `RISK_REJECTED` below), never under this one. Re-arming the remaining protection is always the user's move; cancelling one leg by hand leaves the sibling armed. `PROTECTIVE_SELF_TRADE_SWEEP`: a firing stop that would match the account's own resting liquidity sweeps those resting maker orders out of the way so the protective child can execute. It is delivered on the swept MAKER order's own cancellation event — the resting order carries this reason as it goes terminal — which is what distinguishes it from `SELF_TRADE_PREVENTION`: that one appears on the incoming taker and leaves resting orders untouched. `POSITION_CLOSED`: there was nothing left to reduce. It arises at two different moments. On a fired child already resting in the book, every fill is clamped to the position still reducible at that instant, and a clamp to zero cancels the remainder. At firing time, if the position has already closed or flipped under the stop — or what remains of it is below one tradeable lot — the fire is refused before any child exists, and BOTH legs of the protective pair are cancelled with this reason, on orders that still carry `triggered: false`. `RISK_REJECTED` is the admission-time counterpart of `RISK_CANCELLED`: the child a trigger was about to fire into was refused by the same pre-trade risk checks that return a `RequestErrorCode` on an interactive create. Because no request is waiting on it, the refusal is published on the order instead. Which individual check refused it is NOT published — `cancelReasonMessage` is a fixed explanatory string per `cancelReason`, so do not parse it or branch on it. Like `POSITION_CLOSED` at firing time, it is a pre-child refusal: no child order is created, and BOTH legs of the pair are cancelled with this reason, still carrying `triggered: false`. The consequence is terminal: nothing rests and nothing fills, and the protection is gone — the stop is not retried or re-armed once the account recovers, so re-arming is the user's move. A `GTT` protective stop carries the ordinary `GTT_EXPIRED` when it reaches its expiry boundary, and that boundary sits one settlement headroom BEFORE the signed `expiresAfter` rather than at it: whichever phase the boundary finds — the still-armed trigger, or the fired child resting in the book — is the one cancelled. `POST /v2/cancelAll` cancels a fired child as `MASS_CANCEL` like any other resting order.''', default=None, alias='''cancelReason''')
  cancel_reason_message: Optional[str] = Field(description='''Human-readable explanation of `cancelReason`. Present only when `cancelReason` is present.''', default=None, alias='''cancelReasonMessage''')
  first_fill_id: Optional[str] = Field(description='''Matching-engine fill nonce of the first fill this order produced on entry. Together with fillCount it identifies the fills as a contiguous nonce range [firstFillId, firstFillId + fillCount - 1]. Absent if the order did not fill on entry. For a non-IOC (resting) taker, the same first nonce also appears on the order's taker update in the orderChanges channel; an IOC taker is not published to orderChanges, so this response is the only place its fill range is delivered.''', default=None, alias='''firstFillId''')
  fill_count: Optional[int] = Field(default=None, alias='''fillCount''')
  additional_properties: Optional[dict[str, Any]] = Field(default=None, exclude=True)

  @model_serializer(mode='wrap')
  def custom_serializer(self, handler):
    serialized_self = handler(self)
    additional_properties = getattr(self, "additional_properties")
    if additional_properties is not None:
      for key, value in additional_properties.items():
        # Never overwrite existing values, to avoid clashes
        if not key in serialized_self:
          serialized_self[key] = value

    return serialized_self

  @model_validator(mode='before')
  @classmethod
  def unwrap_additional_properties(cls, data):
    if not isinstance(data, dict):
      data = data.model_dump()
    json_properties = list(data.keys())
    known_object_properties = ['status', 'exec_qty', 'cum_qty', 'order_id', 'client_order_id', 'cancel_reason', 'cancel_reason_message', 'first_fill_id', 'fill_count', 'additional_properties']
    unknown_object_properties = [element for element in json_properties if element not in known_object_properties]
    # Ignore attempts that validate regular models, only when unknown input is used we add unwrap extensions
    if len(unknown_object_properties) == 0: 
      return data
  
    known_json_properties = ['status', 'execQty', 'cumQty', 'orderId', 'clientOrderId', 'cancelReason', 'cancelReasonMessage', 'firstFillId', 'fillCount', 'additionalProperties']
    additional_properties = data.get('additional_properties', {})
    for obj_key in unknown_object_properties:
      if not known_json_properties.__contains__(obj_key):
        additional_properties[obj_key] = data.pop(obj_key, None)
    data['additional_properties'] = additional_properties
    return data

