from __future__ import annotations
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from sdk.async_exec_api.modify_order_message_type import ModifyOrderMessageType
from sdk.async_exec_api.modify_order_request import ModifyOrderRequest
class ModifyOrderRequestMessagePayload(BaseModel):
  type: ModifyOrderMessageType = Field(description='''Message type for modifyOrder request and response''')
  id: str = Field(description='''Client-chosen correlation identifier; must be unique across in-flight requests on the connection.''')
  payload: ModifyOrderRequest = Field(description='''Modifies a live resting order in place. Target by `orderId` when present, otherwise by a non-zero `clientOrderId`; if both are supplied, `orderId` is the lookup key and `clientOrderId` is still the restated immutable client id. The request is a full restate of the post-modify `OrderDetails`: every signed field is sent at its intended post-modify value, and omission never means inherit. Modifiable fields are `limitPx`, `qty`, `postOnly`, `expiresAfter`, and `triggerPx`; all other signed fields are immutable and must match the resting order. If the resting order has a non-zero `clientOrderId`, restate it; omit `clientOrderId` only when the resting order has none. `timeInForce` is immutable: GTC uses `expiresAfter` 0/omitted, while GTT must carry a non-zero future `expiresAfter` greater than `deadline`. Modify is LIMIT-only until native SL/TP trigger modify is available; omit `triggerPx` for LIMIT. `qty` is total order quantity and must be greater than `cumQty`. An identical restate returns `EMPTY_MODIFY_ERROR`; a post-only cross returns `POST_ONLY_WOULD_CROSS_ERROR`; a non-post-only cross may fill immediately. A fresh nonce and EIP-712 signature over the restated order are required.''')
