from __future__ import annotations
from typing import Any, Dict, Optional
from pydantic import model_serializer, model_validator, BaseModel, Field
from sdk.async_exec_api.order_status import OrderStatus
from sdk.async_exec_api.cancel_reason import CancelReason
class ModifyOrderResponse(BaseModel):
  status: OrderStatus = Field(description='''Order status''')
  exec_qty: Optional[str] = Field(default=None, alias='''execQty''')
  cum_qty: Optional[str] = Field(default=None, alias='''cumQty''')
  order_id: str = Field(description='''Order ID — unchanged by the modification (the same ID the order had before).''', alias='''orderId''')
  client_order_id: Optional[str] = Field(description='''Client-provided order ID preserved from order creation, as a decimal string (`uint64`).''', default=None, alias='''clientOrderId''')
  cancel_reason: Optional[CancelReason] = Field(description='''Why an order reached a terminal `CANCELLED` status. `cancelReason` / `cancelReasonMessage` are present if and only if `status` is `CANCELLED`; they are omitted entirely (not `null`, not `""`) otherwise. Matching-engine `UNSPECIFIED` or unknown reasons map to omission. `NO_LIQUIDITY` (IOC executed zero quantity because no fillable liquidity was available at its limit) and `IOC_REMAINDER` (IOC partially filled and the remaining quantity was cancelled because no more executable opposite liquidity was available) are returned on `createOrder` / `modifyOrder` responses; `GTT_EXPIRED`, `USER_CANCEL`, `MASS_CANCEL` and `CANCEL_ALL_AFTER` are delivered on the `walletOrderChanges` stream. `SELF_TRADE_PREVENTION` can appear on `createOrder` / `modifyOrder` responses and on `walletOrderChanges` when a modified resting order crosses as taker. It cancels the aggressor (taker) only; your resting order is left untouched. If an IOC partially fills and its remaining quantity is then cancelled by self-trade prevention, the response keeps the fill quantities and reports `cancelReason: SELF_TRADE_PREVENTION`; `IOC_REMAINDER` is used only when matching stops without a self-cross. `FEED_RESET` is generated by the API layer (not the matching engine): when the market-data feed is reset — e.g. a matching-engine reseed — every resting order is delivered on the `walletOrderChanges` stream as `CANCELLED` with `cancelReason: FEED_RESET`, immediately followed by fresh order events that re-publish your current open orders. It does not mean your orders were cancelled on the exchange; treat it as a signal to discard and rebuild your local order view, reconciling against `GET /v2/wallet/{address}/openOrders` if needed.''', default=None, alias='''cancelReason''')
  cancel_reason_message: Optional[str] = Field(description='''Human-readable explanation of `cancelReason`. Present only when `cancelReason` is present.''', default=None, alias='''cancelReasonMessage''')
  first_fill_id: Optional[str] = Field(description='''Matching-engine fill nonce of the first fill this order produced on entry. Together with fillCount it identifies the fills as a contiguous nonce range [firstFillId, firstFillId + fillCount - 1]. Absent if the order did not fill on entry. For a non-IOC (resting) taker, the same first nonce also appears on the order's taker update in the orderChanges channel; an IOC taker is not published to orderChanges, so this response is the only place its fill range is delivered.''', default=None, alias='''firstFillId''')
  fill_count: Optional[int] = Field(default=None, alias='''fillCount''')
  additional_properties: Optional[dict[str, Any]] = Field(default=None, exclude=True)

  @model_serializer(mode='wrap')
  def custom_serializer(self, handler):
    serialized_self = handler(self)
    additional_properties = getattr(self, "additional_properties")
    if additional_properties is not None:
      for key, value in additional_properties.items():
        # Never overwrite existing values, to avoid clashes
        if not key in serialized_self:
          serialized_self[key] = value

    return serialized_self

  @model_validator(mode='before')
  @classmethod
  def unwrap_additional_properties(cls, data):
    if not isinstance(data, dict):
      data = data.model_dump()
    json_properties = list(data.keys())
    known_object_properties = ['status', 'exec_qty', 'cum_qty', 'order_id', 'client_order_id', 'cancel_reason', 'cancel_reason_message', 'first_fill_id', 'fill_count', 'additional_properties']
    unknown_object_properties = [element for element in json_properties if element not in known_object_properties]
    # Ignore attempts that validate regular models, only when unknown input is used we add unwrap extensions
    if len(unknown_object_properties) == 0:
      return data

    known_json_properties = ['status', 'execQty', 'cumQty', 'orderId', 'clientOrderId', 'cancelReason', 'cancelReasonMessage', 'firstFillId', 'fillCount', 'additionalProperties']
    additional_properties = data.get('additional_properties', {})
    for obj_key in unknown_object_properties:
      if not known_json_properties.__contains__(obj_key):
        additional_properties[obj_key] = data.pop(obj_key, None)
    data['additional_properties'] = additional_properties
    return data
