from __future__ import annotations
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from sdk.async_exec_api.modify_order_message_type import ModifyOrderMessageType
from sdk.async_exec_api.modify_order_request import ModifyOrderRequest
class ModifyOrderRequestMessagePayload(BaseModel): 
  type: ModifyOrderMessageType = Field(description='''Message type for modifyOrder request and response''')
  id: str = Field(description='''Client-chosen correlation identifier; must be unique across in-flight requests on the connection.''')
  payload: ModifyOrderRequest = Field(description='''Modifies a live resting order in place. Target by `orderId` when present, otherwise by a non-zero `clientOrderId`. The JSON Schema validates target presence only; the server enforces the non-zero rule for sole `clientOrderId` targets. The same `clientOrderId` field restates the resting order's immutable client id for signing; if both identifiers are supplied, `orderId` is the lookup key and `clientOrderId` is the restated immutable. If the resting order has no client id, omit `clientOrderId`; do not send a placeholder value. The request is a full restate of the post-modify `OrderDetails`: every signed field is sent at its intended post-modify value, and omission never means inherit. Modifiable fields are class-split: for a `LIMIT` modify they are `limitPx`, `qty`, `postOnly` and `expiresAfter` (`triggerPx` forbidden); for a `STOP_LOSS`/`TAKE_PROFIT` modify ONLY `limitPx` and `triggerPx` are modifiable — `qty` stays omitted, `postOnly=false` is a restated immutable, and so are `timeInForce` and `expiresAfter`: giving a stop a different fired-child time in force, or a different shared expiry, means cancelling it and creating a new one. All other signed fields are immutable and must match the resting order. `timeInForce` is immutable for every class: GTC and IOC omit `expiresAfter`, while GTT must carry a future `expiresAfter` greater than `deadline`. Only an armed trigger (`triggered: false`) is modifiable — once it has fired, the resting child is cancel-only and a modify against it is refused. A re-priced trigger is re-checked against the market's trigger band exactly as at creation, and a `limitPx` outside the band is rejected with `TRIGGER_LIMIT_OUTSIDE_BAND_ERROR`. `triggerPx` is required on a trigger modify and omitted for `LIMIT`. `qty` is omitted on a `STOP_LOSS`/`TAKE_PROFIT` modify (the signed quantity restates the full-position sentinel `±int256.max`, sign from `isBuy`) and required for a `LIMIT` modify, where it is the total order quantity and must be greater than `cumQty`. An identical `LIMIT` restate returns `EMPTY_MODIFY_ERROR`; a trigger restated at unchanged `limitPx` and `triggerPx` is instead accepted and applied, so a stop can be re-signed with a fresh `signature`, `nonce` and `deadline` without moving its prices. A post-only cross returns `POST_ONLY_WOULD_CROSS_ERROR`; a non-post-only cross may fill immediately. A fresh nonce and EIP-712 signature over the restated order are required.''')
