from enum import Enum

class RequestErrorCode(Enum): 
  SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND"
  NO_ACCOUNTS_FOUND = "NO_ACCOUNTS_FOUND"
  NO_PRICES_FOUND_FOR_SYMBOL = "NO_PRICES_FOUND_FOR_SYMBOL"
  INPUT_VALIDATION_ERROR = "INPUT_VALIDATION_ERROR"
  CREATE_ORDER_OTHER_ERROR = "CREATE_ORDER_OTHER_ERROR"
  CANCEL_ORDER_OTHER_ERROR = "CANCEL_ORDER_OTHER_ERROR"
  ORDER_DEADLINE_PASSED_ERROR = "ORDER_DEADLINE_PASSED_ERROR"
  ORDER_DEADLINE_TOO_HIGH_ERROR = "ORDER_DEADLINE_TOO_HIGH_ERROR"
  INVALID_NONCE_ERROR = "INVALID_NONCE_ERROR"
  UNAVAILABLE_MATCHING_ENGINE_ERROR = "UNAVAILABLE_MATCHING_ENGINE_ERROR"
  UNAUTHORIZED_SIGNATURE_ERROR = "UNAUTHORIZED_SIGNATURE_ERROR"
  NUMERIC_OVERFLOW_ERROR = "NUMERIC_OVERFLOW_ERROR"