# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccountType(str, Enum):
    """
    SPOT = account that can only trade spot, MAINPERP = main perp account, SUBPERP = sub perp account
    """

    """
    allowed enum values
    """
    MAINPERP = 'MAINPERP'
    SUBPERP = 'SUBPERP'
    SPOT = 'SPOT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountType from a JSON string"""
        return cls(json.loads(json_str))


