# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DepthType(str, Enum):
    """
    Depth message type. On the public WebSocket, SNAPSHOT is the exact bounded view delivered on subscribe: at most the 100 highest bids and 100 lowest asks (WebSocket has no client-selected limit, and deeper levels are omitted). UPDATE transforms the previous bounded view into the next one. It may include newly visible boundary levels whose underlying quantity did not change and zero-quantity removals for displaced levels that still exist deeper in the exchange book; an underlying change wholly outside the view does not emit an UPDATE. Quantities are absolute, and qty 0 removes that price from the published view. Apply UPDATE frames in order to maintain the exact bounded view; reconnect and resubscribe for a fresh snapshot after interruption. REST depth snapshots use their requested/default limit within the same 1,000-level per-side maximum.
    """

    """
    allowed enum values
    """
    SNAPSHOT = 'SNAPSHOT'
    UPDATE = 'UPDATE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DepthType from a JSON string"""
        return cls(json.loads(json_str))


