# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DepthType(str, Enum):
    """
    SNAPSHOT replaces the current depth view; UPDATE applies changed price levels to that view. See the streaming API marketDepth channel for view limits, absolute quantities, boundary changes, and update handling. REST snapshot limits are documented on GET /v2/market/{symbol}/depth.
    """

    """
    allowed enum values
    """
    SNAPSHOT = 'SNAPSHOT'
    UPDATE = 'UPDATE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DepthType from a JSON string"""
        return cls(json.loads(json_str))


