# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.20
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ExecutionBustReasonSpotPriceDeviationTooLarge(BaseModel):
    """
    ExecutionBustReasonSpotPriceDeviationTooLarge
    """ # noqa: E501
    reason_name: StrictStr = Field(alias="reasonName")
    fill_price: StrictStr = Field(description="Fill price decoded from an 18-decimal fixed-point contract value.", alias="fillPrice")
    oracle_price: StrictStr = Field(description="Oracle price decoded from an 18-decimal fixed-point contract value.", alias="oraclePrice")
    oracle_deviation: StrictStr = Field(description="Oracle deviation threshold decoded from an 18-decimal fixed-point contract value.", alias="oracleDeviation")
    __properties: ClassVar[List[str]] = ["reasonName", "fillPrice", "oraclePrice", "oracleDeviation"]

    @field_validator('reason_name')
    def reason_name_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PriceDeviationTooLarge']):
            raise ValueError("must be one of enum values ('PriceDeviationTooLarge')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionBustReasonSpotPriceDeviationTooLarge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionBustReasonSpotPriceDeviationTooLarge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reasonName": obj.get("reasonName"),
            "fillPrice": obj.get("fillPrice"),
            "oraclePrice": obj.get("oraclePrice"),
            "oracleDeviation": obj.get("oracleDeviation")
        })
        return _obj


