# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class MarketSummary(BaseModel):
    """
    MarketSummary
    """ # noqa: E501
    symbol: Annotated[str, Field(strict=True)] = Field(description="Trading symbol (e.g., BTCRUSDPERP, ETHRUSD)")
    updated_at: Annotated[int, Field(strict=True, ge=0)] = Field(alias="updatedAt")
    long_oi_qty: Annotated[str, Field(strict=True)] = Field(alias="longOiQty")
    short_oi_qty: Annotated[str, Field(strict=True)] = Field(alias="shortOiQty")
    oi_qty: Annotated[str, Field(strict=True)] = Field(alias="oiQty")
    funding_rate: Annotated[str, Field(strict=True)] = Field(alias="fundingRate")
    long_funding_value: Annotated[str, Field(strict=True)] = Field(alias="longFundingValue")
    short_funding_value: Annotated[str, Field(strict=True)] = Field(alias="shortFundingValue")
    funding_rate_velocity: Annotated[str, Field(strict=True)] = Field(alias="fundingRateVelocity")
    volume24h: Annotated[str, Field(strict=True)]
    px_change24h: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="pxChange24h")
    throttled_oracle_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="throttledOraclePrice")
    throttled_pool_price: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="throttledPoolPrice")
    prices_updated_at: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="pricesUpdatedAt")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["symbol", "updatedAt", "longOiQty", "shortOiQty", "oiQty", "fundingRate", "longFundingValue", "shortFundingValue", "fundingRateVelocity", "volume24h", "pxChange24h", "throttledOraclePrice", "throttledPoolPrice", "pricesUpdatedAt"]

    @field_validator('symbol')
    def symbol_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9]+$/")
        return value

    @field_validator('long_oi_qty')
    def long_oi_qty_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    @field_validator('short_oi_qty')
    def short_oi_qty_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    @field_validator('oi_qty')
    def oi_qty_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    @field_validator('funding_rate')
    def funding_rate_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('long_funding_value')
    def long_funding_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('short_funding_value')
    def short_funding_value_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('funding_rate_velocity')
    def funding_rate_velocity_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('volume24h')
    def volume24h_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?$/")
        return value

    @field_validator('px_change24h')
    def px_change24h_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('throttled_oracle_price')
    def throttled_oracle_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    @field_validator('throttled_pool_price')
    def throttled_pool_price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d+(\.\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MarketSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MarketSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "symbol": obj.get("symbol"),
            "updatedAt": obj.get("updatedAt"),
            "longOiQty": obj.get("longOiQty"),
            "shortOiQty": obj.get("shortOiQty"),
            "oiQty": obj.get("oiQty"),
            "fundingRate": obj.get("fundingRate"),
            "longFundingValue": obj.get("longFundingValue"),
            "shortFundingValue": obj.get("shortFundingValue"),
            "fundingRateVelocity": obj.get("fundingRateVelocity"),
            "volume24h": obj.get("volume24h"),
            "pxChange24h": obj.get("pxChange24h"),
            "throttledOraclePrice": obj.get("throttledOraclePrice"),
            "throttledPoolPrice": obj.get("throttledPoolPrice"),
            "pricesUpdatedAt": obj.get("pricesUpdatedAt")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


