# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Optional
from sdk.open_api.models.create_order_request1_any_of import CreateOrderRequest1AnyOf
from sdk.open_api.models.modify_order_request1_any_of import ModifyOrderRequest1AnyOf
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

MODIFYORDERREQUEST1_ANY_OF_SCHEMAS = ["CreateOrderRequest1AnyOf", "ModifyOrderRequest1AnyOf", "object"]

class ModifyOrderRequest1(BaseModel):
    """
    ModifyOrderRequest1
    """

    # data type: object
    anyof_schema_1_validator: Optional[Any] = Field(default=None, description="At least one target identifier is required. If `orderId` is absent, `clientOrderId` must be non-zero.")
    # data type: CreateOrderRequest1AnyOf
    anyof_schema_2_validator: Optional[CreateOrderRequest1AnyOf] = None
    # data type: ModifyOrderRequest1AnyOf
    anyof_schema_3_validator: Optional[ModifyOrderRequest1AnyOf] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[CreateOrderRequest1AnyOf, ModifyOrderRequest1AnyOf, object]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "CreateOrderRequest1AnyOf", "ModifyOrderRequest1AnyOf", "object" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ModifyOrderRequest1.model_construct()
        error_messages = []
        # validate data type: object
        try:
            instance.anyof_schema_1_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: CreateOrderRequest1AnyOf
        if not isinstance(v, CreateOrderRequest1AnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CreateOrderRequest1AnyOf`")
        else:
            return v

        # validate data type: ModifyOrderRequest1AnyOf
        if not isinstance(v, ModifyOrderRequest1AnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ModifyOrderRequest1AnyOf`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ModifyOrderRequest1 with anyOf schemas: CreateOrderRequest1AnyOf, ModifyOrderRequest1AnyOf, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # deserialize data into object
        try:
            # validation
            instance.anyof_schema_1_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_1_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[CreateOrderRequest1AnyOf] = None
        try:
            instance.actual_instance = CreateOrderRequest1AnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ModifyOrderRequest1AnyOf] = None
        try:
            instance.actual_instance = ModifyOrderRequest1AnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ModifyOrderRequest1 with anyOf schemas: CreateOrderRequest1AnyOf, ModifyOrderRequest1AnyOf, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CreateOrderRequest1AnyOf, ModifyOrderRequest1AnyOf, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


