# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.1.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from sdk.open_api.models.side import Side
from typing import Optional, Set
from typing_extensions import Self

class SpotTradeBust(BaseModel):
    """
    SpotTradeBust
    """ # noqa: E501
    symbol: Annotated[str, Field(strict=True)] = Field(description="Trading symbol (e.g., BTCRUSDPERP, WETHRUSD)")
    account_id: Annotated[int, Field(strict=True, ge=0)] = Field(alias="accountId")
    counterparty_account_id: Annotated[int, Field(strict=True, ge=0)] = Field(alias="counterpartyAccountId")
    qty: Annotated[str, Field(strict=True)]
    side: Side
    price: Annotated[str, Field(strict=True)]
    reason: StrictStr = Field(description="Hex-encoded revert reason bytes")
    timestamp: Annotated[int, Field(strict=True, ge=0)]
    transaction_hash: StrictStr = Field(description="Transaction hash", alias="transactionHash")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["symbol", "accountId", "counterpartyAccountId", "qty", "side", "price", "reason", "timestamp", "transactionHash"]

    @field_validator('symbol')
    def symbol_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[A-Za-z0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9]+$/")
        return value

    @field_validator('qty')
    def qty_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d+(\.\d+)?([eE][+-]?\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^\d+(\.\d+)?([eE][+-]?\d+)?$/")
        return value

    @field_validator('price')
    def price_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d+(\.\d+)?([eE][+-]?\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d+(\.\d+)?([eE][+-]?\d+)?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpotTradeBust from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpotTradeBust from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "symbol": obj.get("symbol"),
            "accountId": obj.get("accountId"),
            "counterpartyAccountId": obj.get("counterpartyAccountId"),
            "qty": obj.get("qty"),
            "side": obj.get("side"),
            "price": obj.get("price"),
            "reason": obj.get("reason"),
            "timestamp": obj.get("timestamp"),
            "transactionHash": obj.get("transactionHash")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


