# coding: utf-8

"""
    Reya DEX Trading API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.4.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransferType(str, Enum):
    """
    Purpose of a transfer entry; direction is given by the sign of amount. See GET /v2/wallet/{address}/transfers, Transfer types, for the meaning of each value.
    """

    """
    allowed enum values
    """
    DEPOSIT = 'DEPOSIT'
    WITHDRAWAL = 'WITHDRAWAL'
    TRANSFER = 'TRANSFER'
    POOL_STAKE = 'POOL_STAKE'
    POOL_UNSTAKE = 'POOL_UNSTAKE'
    PERP_TAKER_FEE = 'PERP_TAKER_FEE'
    PERP_REFERRER_REBATE = 'PERP_REFERRER_REBATE'
    PERP_TAKER_REBATE = 'PERP_TAKER_REBATE'
    PERP_POOL_REBATE = 'PERP_POOL_REBATE'
    PERP_FEE = 'PERP_FEE'
    SPOT_EXECUTION = 'SPOT_EXECUTION'
    AUTO_EXCHANGE = 'AUTO_EXCHANGE'
    AUTO_EXCHANGE_INSURANCE_FEE = 'AUTO_EXCHANGE_INSURANCE_FEE'
    LIQUIDATION_INSURANCE_FEE = 'LIQUIDATION_INSURANCE_FEE'
    LIQUIDATION_BACKSTOP_FEE = 'LIQUIDATION_BACKSTOP_FEE'
    LIQUIDATION_LIQUIDATOR_REWARD = 'LIQUIDATION_LIQUIDATOR_REWARD'
    LIQUIDATION_KEEPER_REWARD = 'LIQUIDATION_KEEPER_REWARD'
    LIQUIDATION_BID_FEE = 'LIQUIDATION_BID_FEE'
    INSURANCE_FUND_COVERAGE = 'INSURANCE_FUND_COVERAGE'
    POOL_MERGE = 'POOL_MERGE'
    OTHER = 'OTHER'

    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransferType from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value: object) -> Self:
        """Resolve a member added by the server since this SDK was generated."""
        return cls.UNKNOWN


